[package]
name = "kg"
version = "1.0.0"
authors = ["GaspardP"]
edition = "2018"

[dependencies]
nix = "0.24.1"
termios = "0.3.2"
unicode-segmentation = "1.9.0"
tree-sitter="0.20.8"
tree-sitter-c = "0.20.1"
tree-sitter-rust = "0.20.1"

[build-dependencies]
# Required by tree-siiter
cc="1.0"